[package]
name = "auto-js-doc"
version = "0.0.0-alpha.1"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[build-dependencies]
cc="*"

[dependencies]
tree-sitter = "0.22"
tree-sitter-typescript = "0.21"

[[bin]]
name = "auto-js-doc"
path = "src/lib.rs"
