app = 'auto-js-doc'
primary_region = 'lhr'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = false
  processes = ['app']
[[vm]]
  size = 'shared-cpu-1x'
